import styled from "styled-components";
const img = "https://www.themoviedb.org/t/p/w1280"
export const MoviesInfo = styled.div`
      box-sizing: border-box;
    /* background-image: url("https://wallpapercave.com/wp/gJQg1va.jpg"); */
    background-image: url(${img}${props => props.bgimg});
    background-blend-mode:darken; 
    background-color: rgba(0, 0, 0, 0.822);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    background-position: center;    
    background-size: cover;
    background-attachment: fixed;
`
